In [ ]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [2]:
# Define the data as a list of lists
data = [
    ['Abule Egba', 'Km 26, Old Lagos-Abeokuta Express Way, Abule Egba'],
    ['Admiralty Way, Lekki', '10 Admiralty Way, Lekki Phase I'],
    ['Agidingbi', 'Plot 34, Lateef Jakande Road, Agidingbi, Ikeja'],
    ['Aguda, Surulere', 'No. 2 Kusimo Street, NEPA Junction, Aguda, Surulere'],
    ['Agungi', 'No 23 Ajiran Road, Agungi, Lekki'],
    ['Ajah', '5 Addo - Langbasa - Badore Road, Ajah'],
    ['Ajose Adeogun', '271A Ajose Adeogun St, Victoria Island'],
    ['Akoka', '41 St. Finbarrs Road, Akoka, Yaba'],
    ['Akowonjo', '149 Akowonjo Road, Egbeda'],
    ['Alapere, Ketu', 'Oando Filling Station, Alapere, Ketu'],
    ['Alimosho', '1 Kokumo Road, (next to Mosolasi Bus Stop), off Ipaja Road, Alimosho'],
    ['Awolowo I', '190 Awolowo Rd, Ikoyi'],
    ['Badore, Ajah', '28 Badore Road, along Ajah/Badore Road, Ado Village, Ajah'],
    ['Bode Thomas', '73 Bode Thomas St, Surulere'],
    ['Con Oil, Ikeja', 'Conoil Filling Station, 2 Oba Akinjobi Way, Ikeja'],
    ['Diya, Gbagada', '48 Diya Street, Gbagada'],
    ['Domino E-Centre', '2nd Floor Domino Plaza, Commercial Avenue, Sabo, Yaba'],
    ['Egbe Road, Ejigbo', '70 Egbe Road, Ejigbo'],
    ['Ekoro', '55 Ekoro Road, Agbelekale Bus Stop'],
    ['Entourage Mall', 'Entourage Mall, Road 14, Adebayo Doherty, Lekki Phase 1'],
    ['Eterna, Lekki Jakande Roundabout', 'Eterna Filling Station, Lekki Jakande Roundabout, Lekki Epe Expressway'],
    ['Festac', '22 Rd, Festac Town'],
    ['Freedom Way, Lekki', '40 Freedom Way, Lekki'],
    ['Gbagada', 'Plot 295 Gbagada - Oworonshoki Expressway, Gbagada'],
    ['Heyden Ibafo', 'Heyden Filling Station, Lagos-Ibadan Expressway, Ibafo Bus Stop'],
    ['Idimu', '230 Egbeda â€“ Idimu Road, Car Wash Bus Stop, Egbeda'],
    ['Ikeja City Mall', 'Ikeja City Mall, Alausa, Obafemi Awolowo Way, Ikeja'],
    ['Ikorodu', 'Plot 19, TOS Benson Road, Ojogbe Ikorodu'],
    ['Ikotun-Idumu Road', '99 Ikotun - Idimu Road, Ile-Epo Bus Stop, Ikotun'],
    ['Ilupeju', '12 Coker Road, Ilupeju'],
    ['Ipaja-Ayobo Road', '259 Ipaja Ayobo Road, Ipaja'],
    ['Ire-Akari', '32 Ire Akari Estate Road, Isolo'],
    ['Isawo Road', 'Isawo Road, Asolo, Ikorodu'],
    ['Jibowu', '10 Ikorodu Road, Jibowu, Yaba'],
    ['Joel Ogunnaike', '8a Joel Ogunaike Street, GRA, Ikeja'],
    ['Magodo', 'Beside First Bank, CMD Road, Magodo'],
    ['Marina', 'Oando Filling Station, Marina'],
    ['MM2 Lagos', 'Muritala Mohammed Domestic Airport'],
    ['MMIA', 'Muritala Muhammed International Airport, Ikeja'],
    ['Mobil Ogba', 'Mobil Filling Station, Ijaiye Road, Ogba'],
    ['Oba Akran', '42 Oba Akran Road, Ikeja'],
    ['Ogudu', '124 Ogudu Road, Ojota'],
    ['Ogunlana Drive', '36 Ogunlana Drive Surulere'],
    ['Oke Afa', 'Plot No. 7, Egbe Road, Oke Afa'],
    ['Okota', '8 Okota Rd, Oshodi-Isolo'],
    ['Omole', 'Plot 86, Block Iv Ojodu-Berger Road, Ile-Epo B/Stop, Omole Phase 1'],
    ['Oniru', 'Plot 3 Block III, Yesuf Abiodun Way, (beside Four Points Hotels) Victoria Island'],
    ['Opebi', '37A Opebi Road, Opposite Adebola House, Ikeja'],
    ['Osolo Way', '18 Osolo Way, Ajao Estate'],
    ['Palmgrove Shipeolu', '30/32 Shipeolu Street, Shomolu'],
    ['Sky Mall Sangotedo', 'KM 46 Lekki - Epe Expressway Farm Bus-Stop Sangotedo, Eti-Osa'],
    ['Tejuosho', 'Exquisite Plaza, 30-32 Ojuelegba Road, Tejuosho, Yaba'],
    ['Total, Lekki', 'Total Filling station by Nicon Town Salem Bus Stop'],
    ['VGC', 'Heyden Filling Station, Lekki- Epe Expressway, VGC']
]

# Create a DataFrame with appropriate column names
df = pd.DataFrame(data, columns=['Location', 'Address'])

df.head()

               Location                                            Address
0            Abule Egba  Km 26, Old Lagos-Abeokuta Express Way, Abule Egba
1  Admiralty Way, Lekki                    10 Admiralty Way, Lekki Phase I
2             Agidingbi     Plot 34, Lateef Jakande Road, Agidingbi, Ikeja
3       Aguda, Surulere  No. 2 Kusimo Street, NEPA Junction, Aguda, Sur...
4                Agungi                   No 23 Ajiran Road, Agungi, Lekki

In [3]:
df.shape

(54, 2)

In [4]:
# Add "Lagos, Nigeria" to each value in the 'Address' column
df['Address'] = df['Address'] + ', Lagos, Nigeria'

# Display the updated DataFrame to check the result
df[['Location', 'Address']].head()

               Location                                            Address
0            Abule Egba  Km 26, Old Lagos-Abeokuta Express Way, Abule E...
1  Admiralty Way, Lekki    10 Admiralty Way, Lekki Phase I, Lagos, Nigeria
2             Agidingbi  Plot 34, Lateef Jakande Road, Agidingbi, Ikeja...
3       Aguda, Surulere  No. 2 Kusimo Street, NEPA Junction, Aguda, Sur...
4                Agungi   No 23 Ajiran Road, Agungi, Lekki, Lagos, Nigeria

In [5]:
import pandas as pd
from geopy.geocoders import GoogleV3
import time

# Your Google Maps API key
api_key = 'AIzaSyBYLFok9qCkBoScI9EpU0qjMM-VQjVwmBQ'

# Initialize the GoogleV3 geocoder
geolocator = GoogleV3(api_key=api_key)

# Function to get longitude and latitude for an address
def get_coordinates(address):
    try:
        location = geolocator.geocode(address)
        if location:
            return location.latitude, location.longitude
        else:
            return None, None
    except Exception as e:
        print(f"Error fetching coordinates for {address}: {e}")
        return None, None


# Apply the get_coordinates function to each address in the DataFrame
df['Latitude'], df['Longitude'] = zip(*df['Address'].apply(get_coordinates))

In [6]:
df.head()

,Location,Address,Latitude,Longitude
0,Abule Egba,"Km 26, Old Lagos-Abeokuta Express Way, Abule E...",6.618764,3.300238
1,"Admiralty Way, Lekki","10 Admiralty Way, Lekki Phase I, Lagos, Nigeria",6.440137,3.455549
2,Agidingbi,"Plot 34, Lateef Jakande Road, Agidingbi, Ikeja...",6.627280,3.354148
3,"Aguda, Surulere","No. 2 Kusimo Street, NEPA Junction, Aguda, Sur...",6.495899,3.345143
4,Agungi,"No 23 Ajiran Road, Agungi, Lekki, Lagos, Nigeria",6.442276,3.515728

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Location   54 non-null     object
 1   Address    54 non-null     object
 2   Latitude   54 non-null     float64
 3   Longitude  54 non-null     float64
dtypes: float64(2), object(2)
memory usage: 1.8+ KB

In [8]:
# Convert df to GeoDataFrame
df['geometry'] = df.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
df_gdf = gpd.GeoDataFrame(df, geometry='geometry', crs='EPSG:4326')  # Assuming WGS84 CRS

In [9]:
df_gdf.to_file("chicken_rep_lagos_branch.geojson", driver="GeoJSON")

In [10]:
import pandas as pd

# Define the path to the CSV file
csv_file_path = 'lagos_lga.csv'

# Read the CSV file into a DataFrame
lagos_lga_df = pd.read_csv(csv_file_path)

# Display the first few rows of the DataFrame
lagos_lga_df.head()

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,NGA.25.1_1,NGA,Nigeria,NGA.25_1,Lagos,NaN,Agege,NaN,NaN,Local Authority,Local Authority,NaN,NaN,POLYGON ((3.3013529790001144 6.620390892000103...
1,NGA.25.2_1,NGA,Nigeria,NGA.25_1,Lagos,NaN,Ajeromi/Ifelodun,NaN,NaN,Local Authority,Local Authority,NaN,NaN,"POLYGON ((3.322557925000126 6.446716786000081,..."
2,NGA.25.3_1,NGA,Nigeria,NGA.25_1,Lagos,NaN,Alimosho,NaN,NaN,Local Authority,Local Authority,NaN,NaN,"POLYGON ((3.289611101000105 6.672671795000156,..."
3,NGA.25.4_1,NGA,Nigeria,NGA.25_1,Lagos,NaN,Amuwo Odofin,NaN,NaN,Local Authority,Local Authority,NaN,NaN,"POLYGON ((3.307024002000105 6.477795125000171,..."
4,NGA.25.5_1,NGA,Nigeria,NGA.25_1,Lagos,NaN,Apapa,NaN,NaN,Local Authority,Local Authority,NaN,NaN,"POLYGON ((3.322557925000126 6.446716786000081,..."

In [11]:
lagos_lga_df.columns

Index(['GID_2', 'GID_0', 'COUNTRY', 'GID_1', 'NAME_1', 'NL_NAME_1', 'NAME_2',
       'VARNAME_2', 'NL_NAME_2', 'TYPE_2', 'ENGTYPE_2', 'CC_2', 'HASC_2',
       'geometry'],
      dtype='object')

In [12]:
import geopandas as gpd
from shapely import wkt

# Assuming your geometries are in WKT (Well-Known Text) format
lagos_lga_df['geometry'] = lagos_lga_df['geometry'].apply(wkt.loads)

# Convert to GeoDataFrame
lagos_lga_gdf = gpd.GeoDataFrame(lagos_lga_df, geometry='geometry')

# Set the CRS (if you know it) - commonly WGS84 (EPSG:4326)
lagos_lga_gdf.set_crs(epsg=4326, inplace=True)

# Save as GeoJSON
lagos_lga_gdf.to_file("chicken_rep_lagos_branch.geojson", driver="GeoJSON")

In [13]:
df.columns

Index(['Location', 'Address', 'Latitude', 'Longitude', 'geometry'], dtype='object')

In [14]:
# Perform spatial join using the correct 'predicate' argument
merged_gdf = gpd.sjoin(df_gdf, lagos_lga_gdf[['NAME_2', 'geometry']], how='left', predicate='within')

# Rename columns for clarity
merged_gdf = merged_gdf.rename(columns={'NAME_2': 'LGA', 'geometry_right': 'LGA Geometry'})

# Drop unnecessary columns
final_df = merged_gdf[['Location', 'Address', 'Latitude', 'Longitude', 'LGA', 'geometry']].rename(columns={'geometry': 'LGA Geometry'})

In [15]:
final_df.head()

,Location,Address,Latitude,Longitude,LGA,LGA Geometry
0,Abule Egba,"Km 26, Old Lagos-Abeokuta Express Way, Abule E...",6.618764,3.300238,Alimosho,POINT (3.30024 6.61876)
1,"Admiralty Way, Lekki","10 Admiralty Way, Lekki Phase I, Lagos, Nigeria",6.440137,3.455549,Eti-Osa,POINT (3.45555 6.44014)
2,Agidingbi,"Plot 34, Lateef Jakande Road, Agidingbi, Ikeja...",6.627280,3.354148,Ikeja,POINT (3.35415 6.62728)
3,"Aguda, Surulere","No. 2 Kusimo Street, NEPA Junction, Aguda, Sur...",6.495899,3.345143,Surulere,POINT (3.34514 6.4959)
4,Agungi,"No 23 Ajiran Road, Agungi, Lekki, Lagos, Nigeria",6.442276,3.515728,Eti-Osa,POINT (3.51573 6.44228)

In [16]:
final_df.to_file("chicken_rep_lagos_branch.geojson", driver="GeoJSON")

In [17]:
final_df['LGA'].unique()

array(['Alimosho', 'Eti-Osa', 'Ikeja', 'Surulere', 'Mainland', 'Kosofe',
       'Shomolu', 'Oshodi/Isolo', 'Amuwo Odofin', 'Ikorodu', 'Apapa',
       'Mushin', 'Ibeju-Lekki'], dtype=object)

In [18]:
import osmnx as ox

In [19]:
place_name = "Lagos, Nigeria"
G = ox.graph_from_place(place_name, network_type='drive')

In [20]:
# Project graph to a local CRS that uses meters
G_proj = ox.project_graph(G)
print(f"Projected graph CRS: {G_proj.graph['crs']}")

Projected graph CRS: EPSG:32631

In [21]:
# Drop the old 'LGA Geometry' column if you don't need it anymore
final_df = final_df.drop(columns=['LGA Geometry'])

In [22]:
import geopandas as gpd
from shapely.geometry import Point

# Step 1: Create a geometry column from longitude and latitude
final_df['geometry'] = final_df.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)

# Step 2: Set the initial CRS to WGS84 (EPSG:4326) for latitude and longitude coordinates
final_df = gpd.GeoDataFrame(final_df, geometry='geometry', crs='EPSG:4326')

final_df.to_file("chicken_rep_lagos_branch.geojson", driver="GeoJSON")

In [23]:
# Project the GeoDataFrame to the same CRS as the projected graph
gdf_proj = final_df.to_crs(G_proj.graph['crs'])
print(f"Properties CRS after projection: {gdf_proj.crs}")

Properties CRS after projection: EPSG:32631

In [24]:
# Function to calculate the distance to the nearest road in meters
def get_distance_to_road_meters(geom):
    # Find the nearest edge and its distance
    nearest = ox.distance.nearest_edges(G_proj, geom.x, geom.y, return_dist=True)
    # The distance is the second element in the tuple
    return nearest[1]  # Now in meters since we're using a projected CRS

# Apply the function to calculate the distance to the nearest road for each branch
gdf_proj['distance_to_road_m'] = gdf_proj['geometry'].apply(get_distance_to_road_meters)

In [25]:
# Copy the calculated distances back to the original GeoDataFrame if needed
final_df['distance_to_road_m'] = gdf_proj['distance_to_road_m']

In [26]:
# Save the enriched dataset with road network features
final_df.to_file("chicken_rep_lagos_branch.geojson", driver="GeoJSON")

In [27]:
# Calculate node degree (number of connected roads at each intersection)
node_degrees = dict(G.degree())

# Add degree of nearest node to each property
def get_node_degree(geom):
    nearest_node = ox.distance.nearest_nodes(G, geom.x, geom.y)
    return node_degrees[nearest_node]

final_df['node_degree'] = final_df['geometry'].apply(get_node_degree)

In [28]:
# Save the enriched dataset with road network features
final_df.to_file("chicken_rep_lagos_branch.geojson", driver="GeoJSON")

In [30]:
import geopandas as gpd
from shapely.geometry import LineString, Point


# Convert network to GeoDataFrame of edges
edges = []
for u, v, key, data in G.edges(keys=True, data=True):
    if 'geometry' in data:
        # If the edge has a geometry attribute
        geom = data['geometry']
    else:
        # Create a line from node coordinates
        from_point = Point((G.nodes[u]['x'], G.nodes[u]['y']))
        to_point = Point((G.nodes[v]['x'], G.nodes[v]['y']))
        geom = LineString([from_point, to_point])
    
    # Add length if not present
    if 'length' not in data:
        data['length'] = geom.length
        
    edges.append((u, v, key, data, geom))

# Create GeoDataFrame
gdf_edges = gpd.GeoDataFrame(
    [{'u': u, 'v': v, 'key': k, 'length': d['length']} for u, v, k, d, _ in edges],
    geometry=[g for _, _, _, _, g in edges]
)
gdf_edges.crs = G.graph['crs']

# Calculate road density for each property
def calculate_road_density(geom, buffer_distance=500):
    """Calculate road density within a buffer area around a property"""
    # Create buffer
    buffer = geom.buffer(buffer_distance)
    
    # Get roads within buffer
    roads_in_buffer = gdf_edges[gdf_edges.intersects(buffer)]
    
    # Calculate total road length (in meters)
    total_road_length = roads_in_buffer['length'].sum()
    
    # Calculate buffer area (in square meters)
    buffer_area = buffer.area
    
    # Calculate density (meters of road per square meter)
    density = total_road_length / buffer_area if buffer_area > 0 else 0
    
    # Convert to km/kmÂ² for easier interpretation
    density_km = density * 1000000  # roads in km per kmÂ²
    
    return density_km

# Apply to each property
final_df['road_density_500m'] = final_df['geometry'].apply(
    lambda x: calculate_road_density(x, buffer_distance=500)
)

In [31]:
# Save the enriched dataset with road network features
final_df.to_file("chicken_rep_lagos_branch.geojson", driver="GeoJSON")

In [32]:
final_df.columns

Index(['Location', 'Address', 'Latitude', 'Longitude', 'LGA', 'geometry',
       'distance_to_road_m', 'node_degree', 'road_density_500m'],
      dtype='object')

In [47]:
import googlemaps
import pandas as pd

# Initialize Google Maps client with your API key
gmaps = googlemaps.Client(key='AIzaSyBYLFok9qCkBoScI9EpU0qjMM-VQjVwmBQ')  

# Function to get nearby businesses using Google Places API
def get_nearby_businesses(lat, lon, radius=2000, type_of_business="restaurant"):
    places_result = gmaps.places_nearby(
        location=(lat, lon),
        radius=radius,
        type=type_of_business
    )
    
    places_data = []
    for place in places_result['results']:
        name = place.get('name')
        business_type = place.get('types')
        location = place.get('geometry', {}).get('location', {})
        lat = location.get('lat')
        lon = location.get('lng')
        rating = place.get('rating')
        places_data.append([name, business_type, lat, lon, rating])

    df_places = pd.DataFrame(places_data, columns=['Name', 'Business Type', 'Latitude', 'Longitude', 'Rating'])
    return df_places

In [48]:
# Loop through each row in final_df and get nearby businesses for each location
all_places = []
for index, row in final_df.iterrows():
    lat = row['Latitude']
    lon = row['Longitude']
    nearby_businesses = get_nearby_businesses(lat, lon)
    nearby_businesses['Location'] = row['Location']  # Add the location to the businesses data
    all_places.append(nearby_businesses)

# Concatenate all places into one DataFrame
df_nearby_businesses = pd.concat(all_places, ignore_index=True)
df_nearby_businesses.head()

,Name,Business Type,Latitude,Longitude,Rating,Location
0,Big Bites Shawarma,"[restaurant, food, point_of_interest, establis...",6.619572,3.301499,5.0,Abule Egba
1,Mc Aruna,"[restaurant, food, point_of_interest, establis...",6.619631,3.301888,NaN,Abule Egba
2,Tantalizers - Iyana Ipaja,"[restaurant, food, point_of_interest, establis...",6.614727,3.298132,3.5,Abule Egba
3,Sweet Sensation Confectionery,"[restaurant, food, point_of_interest, establis...",6.616952,3.312696,4.3,Abule Egba
4,All African Dishes,"[restaurant, food, point_of_interest, establis...",6.622821,3.313496,3.8,Abule Egba

In [49]:
df_nearby_businesses.columns

Index(['Name', 'Business Type', 'Latitude', 'Longitude', 'Rating', 'Location'], dtype='object')

In [50]:
# Convert df to GeoDataFrame
df_nearby_businesses['geometry'] = df_nearby_businesses.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
df_nearby_businesses = gpd.GeoDataFrame(df_nearby_businesses, geometry='geometry', crs='EPSG:4326')  # Assuming WGS84 CRS

In [51]:
df_nearby_businesses.to_file("df_nearby_businesses.geojson", driver="GeoJSON")

In [5]:
import geopandas as gpd

# Load the GeoJSON file into a GeoDataFrame
file_path = "chicken_rep_lagos_branch.geojson"  # Replace with the correct path if needed
final_df = gpd.read_file(file_path)

# Display the first few rows of the GeoDataFrame
final_df.columns

Index(['Location', 'Address', 'Latitude', 'Longitude', 'LGA',
       'distance_to_road_m', 'node_degree', 'road_density_500m', 'geometry'],
      dtype='object')

In [7]:
import osmnx as ox
import pandas as pd
import numpy as np
from shapely.geometry import Point
from geopy.distance import geodesic

In [26]:
def get_nearby_pois(lat, lon, tags, radius=2000):
    try:
        point = (lat, lon)
        north, south, east, west = ox.utils_geo.bbox_from_point(point, dist=radius)
        bbox = (north, south, east, west)
        pois = ox.features.features_from_bbox(bbox, tags)
        pois['distance'] = pois.apply(
            lambda row: geodesic(point, (row['geometry'].centroid.y, row['geometry'].centroid.x)).meters,
            axis=1
        )
        pois = pois[pois['distance'] <= radius]
        return pois
    except Exception as e:
        print(f"Error for location ({lat}, {lon}): {e}")
        return pd.DataFrame()  # Return empty DataFrame

In [27]:
tags = {
    'shop': ['mall', 'supermarket', 'market', 'convenience', 'department_store', 'grocery'],
    'office': ['company', 'coworking', 'government'],
    'amenity': ['marketplace', 'post_office', 'bank', 'atm', 'school', 'university', 'hospital', 'clinic'],
    'building': ['retail', 'commercial', 'office', 'civic'],
    'landuse': ['commercial', 'retail']
}

In [28]:
all_pois = []
for index, row in final_df.iterrows():
    lat = row['Latitude']
    lon = row['Longitude']
    try:
        pois = get_nearby_pois(lat, lon, tags)
        if not pois.empty:
            pois['branch_location'] = row['Location']
            pois['branch_latitude'] = lat
            pois['branch_longitude'] = lon
            all_pois.append(pois)
            print(f"Success for location: {row['Location']}")
        else:
            print(f"No POIs found for location: {row['Location']}")
    except Exception as e:
        print(f"Error for location {row['Location']}: {e}")

Success for location: Abule Egba
Success for location: Admiralty Way, Lekki
Success for location: Agidingbi
Success for location: Aguda, Surulere
Success for location: Agungi
Success for location: Ajah
Success for location: Ajose Adeogun
Success for location: Akoka
Success for location: Akowonjo
Success for location: Alapere, Ketu
Success for location: Alimosho
Success for location: Awolowo I
Success for location: Badore, Ajah
Success for location: Bode Thomas
Success for location: Con Oil, Ikeja
Success for location: Diya, Gbagada
Success for location: Domino E-Centre
Success for location: Egbe Road, Ejigbo
Success for location: Ekoro
Success for location: Entourage Mall
Success for location: Eterna, Lekki Jakande Roundabout
Success for location: Festac
Success for location: Freedom Way, Lekki
Success for location: Gbagada
Success for location: Heyden Ibafo
Success for location: Idimu
Success for location: Ikeja City Mall
Success for location: Ikorodu
Success for location: Ikotun-Idumu Road
Success for location: Ilupeju
Success for location: Ipaja-Ayobo Road
Success for location: Ire-Akari
Success for location: Isawo Road
Success for location: Jibowu
Success for location: Joel Ogunnaike
Success for location: Magodo
Success for location: Marina
Success for location: MM2 Lagos
Success for location: MMIA
Success for location: Mobil Ogba
Success for location: Oba Akran
Success for location: Ogudu
Success for location: Ogunlana Drive
Success for location: Oke Afa
Success for location: Okota
Success for location: Omole
Success for location: Oniru
Success for location: Opebi
Success for location: Osolo Way
Success for location: Palmgrove Shipeolu
Success for location: Sky Mall Sangotedo
Success for location: Tejuosho
Success for location: Total, Lekki
Success for location: VGC

In [31]:
# Concatenate all POIs into a single DataFrame
nearby_pois_df = pd.concat(all_pois, ignore_index=True)

In [32]:
# Create Point geometries from the Latitude and Longitude columns
geometry = [Point(xy) for xy in zip(nearby_pois_df['Longitude'], nearby_pois_df['Latitude'])]

# Convert the DataFrame to a GeoDataFrame
nearby_pois_gdf = gpd.GeoDataFrame(nearby_pois_df, geometry=geometry, crs="EPSG:4326")

In [33]:
nearby_pois_gdf.to_file("df_nearby_poi.geojson", driver="GeoJSON")

In [34]:
nearby_pois_gdf.head()

,geometry,amenity,atm,name,brand,brand:wikidata,brand:wikipedia,addr:housenumber,addr:street,operator,...,currency:GBP,currency:NGN,currency:USD,payment:credit_cards,payment:visa,start_date,payment:american_express,payment:cheque,rooms,stars
0,POINT EMPTY,bank,yes,First Bank,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,POINT EMPTY,bank,NaN,UBA,UBA,Q513457,en:United Bank for Africa,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,POINT EMPTY,bank,NaN,Wema Bank,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,POINT EMPTY,bank,NaN,Fidelity Bank,Fidelity Bank,Q5446777,en:Fidelity Bank Nigeria,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,POINT EMPTY,school,NaN,Folbim High School,NaN,NaN,NaN,166,Ipaja Road,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
nearby_pois_gdf['amenity'].unique()

array(['bank', 'school', 'hospital', 'marketplace', nan, 'clinic',
       'events_venue', 'fuel', 'atm', 'police', 'post_office',
       'university', 'community_centre', 'place_of_worship', 'restaurant',
       'cafe'], dtype=object)

In [43]:
amenity_mapping = {
    'bank': 'financial',
    'atm': 'financial',
    'post_office': 'services',
    
    'restaurant': 'food_service',
    'cafe': 'food_service',
    
    'school': 'education',
    'university': 'education',
    
    'hospital': 'healthcare',
    'clinic': 'healthcare',
    
    'marketplace': 'retail',
    
    'events_venue': 'entertainment',
    'community_centre': 'community',
    'place_of_worship': 'community',
    
    'police': 'government',
    
    'fuel': 'transportation'
}

# Apply mapping where amenity exists
nearby_pois_df['amenity_category'] = nearby_pois_df['amenity'].map(amenity_mapping)

In [45]:
# Filter out restaurants if you want to remove them completely
nearby_pois_df = nearby_pois_df[nearby_pois_df['amenity'] != 'restaurant']

In [36]:
list(nearby_pois_gdf.columns)

['geometry',
 'amenity',
 'atm',
 'name',
 'brand',
 'brand:wikidata',
 'brand:wikipedia',
 'addr:housenumber',
 'addr:street',
 'operator',
 'operator:type',
 'landuse',
 'building',
 'addr:city',
 'alt_name',
 'contact:phone',
 'healthcare',
 'website',
 'distance',
 'branch_location',
 'branch_latitude',
 'branch_longitude',
 'addr:postcode',
 'name:zh',
 'opening_hours',
 'phone',
 'shop',
 'drive_through',
 'office',
 'internet_access',
 'height',
 'wikidata',
 'wikipedia',
 'tourism',
 'email',
 'alt_name:en',
 'branch',
 'official_name',
 'level',
 'building:levels',
 'type',
 'note',
 'contact:website',
 'int_name',
 'description',
 'source:name',
 'source:operator',
 'name:en',
 'source',
 'Creative_Lagos',
 'parking',
 'addr:country',
 'addr:place',
 'payment:notes',
 'nohousenumber',
 'survey:date',
 'wheelchair',
 'healthcare:speciality',
 'short_name',
 'surface',
 'health_facility:type',
 'house',
 'smoking',
 'image',
 'fixme',
 'beds',
 'emergency',
 'staff_count:doctors',
 'staff_count:nurses',
 'name:pcm',
 'facility_manager',
 'source:position',
 'status',
 'isced:level',
 'operator:wikidata',
 'cash_in',
 'operator:wikipedia',
 'addr:floor',
 'government',
 'layer',
 'club',
 'man_made',
 'payment:cash',
 'internet_access:fee',
 'outdoor_seating',
 'addr:housename',
 'payment:debit_cards',
 'payment:maestro',
 'payment:mastercard',
 'addr:state',
 'building:part',
 'cuisine',
 'barrier',
 'product',
 'grades',
 'leisure',
 'sport',
 'boundary',
 'contact:facebook',
 'mobile',
 'denomination',
 'religion',
 'Latitude',
 'Longitude',
 'min_age',
 'currency:EUR',
 'currency:GBP',
 'currency:NGN',
 'currency:USD',
 'payment:credit_cards',
 'payment:visa',
 'start_date',
 'payment:american_express',
 'payment:cheque',
 'rooms',
 'stars']

In [37]:
columns_to_keep = [
    'geometry', 'distance', 'branch_location', 'branch_latitude', 'branch_longitude',
    'name', 'amenity', 'shop', 'building', 'landuse', 'office',
    'brand', 'operator', 'opening_hours', 'building:levels', 'tourism', 'healthcare', 'drive_through', 'parking',
    'addr:street', 'addr:city', 'addr:postcode',
    'wheelchair', 'internet_access', 'outdoor_seating'
]

# Keep only columns that exist in the dataframe
existing_columns = [col for col in columns_to_keep if col in nearby_pois_df.columns]
nearby_pois_df = nearby_pois_df[existing_columns]

In [48]:
# Rename 'transportation' to 'filling_station' in the 'amenity_category' column
nearby_pois_df['amenity_category'] = nearby_pois_df['amenity_category'].replace('transportation', 'filling_station')

# Verify the changes
print(nearby_pois_df['amenity_category'].value_counts())

amenity_category
education          426
healthcare         372
financial          365
filling_station     59
retail              48
entertainment        8
community            7
services             5
government           4
food_service         1
Name: count, dtype: int64

In [49]:
nearby_pois_df.to_file("df_nearby_poi.geojson", driver="GeoJSON")

In [47]:
nearby_pois_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 2685 entries, 0 to 2688
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   geometry          2685 non-null   geometry
 1   distance          2685 non-null   float64
 2   branch_location   2685 non-null   object
 3   branch_latitude   2685 non-null   float64
 4   branch_longitude  2685 non-null   float64
 5   name              1798 non-null   object
 6   amenity           1295 non-null   object
 7   shop              154 non-null    object
 8   building          673 non-null    object
 9   landuse           911 non-null    object
 10  office            130 non-null    object
 11  brand             164 non-null    object
 12  operator          303 non-null    object
 13  opening_hours     58 non-null     object
 14  building:levels   87 non-null     object
 15  tourism           91 non-null     object
 16  healthcare        72 non-null     object
 17  drive_through     12 non-null     object
 18  parking           3 non-null      object
 19  addr:street       689 non-null    object
 20  addr:city         555 non-null    object
 21  addr:postcode     119 non-null    object
 22  wheelchair        13 non-null     object
 23  internet_access   8 non-null      object
 24  outdoor_seating   1 non-null      object
 25  amenity_category  1295 non-null   object
dtypes: float64(3), geometry(1), object(22)
memory usage: 566.4+ KB